In [4]:
from nba_api.stats.endpoints import playercareerstats
import pandas as pd
from nba_api.stats.static import players
from nba_api.stats.static import players
import pandas as pd
from bs4 import BeautifulSoup
import requests

### Players stats

In [5]:
players = players.get_players()

# Convert active players data into a DataFrame
players_df = pd.DataFrame(players)

# Display the DataFrame
players_df=players_df[['id','full_name']]
players_df

           id            full_name
0       76001       Alaa Abdelnaby
1       76002      Zaid Abdul-Aziz
2       76003  Kareem Abdul-Jabbar
3          51   Mahmoud Abdul-Rauf
4        1505    Tariq Abdul-Wahad
...       ...                  ...
4895  1627790           Ante Zizic
4896    78647             Jim Zoet
4897    78648            Bill Zopf
4898  1627826          Ivica Zubac
4899    78650           Matt Zunic

[4900 rows x 2 columns]

In [6]:
career_stats_list = []
for index, row in players_df.iterrows():
    player_id = row['id']
    career = playercareerstats.PlayerCareerStats(player_id=str(player_id)) 
    career_stats_dict = career.get_dict()
    player_stats = career_stats_dict['resultSets'][0]['rowSet']
    

    career_stats_list.extend(player_stats)

KeyboardInterrupt:

In [7]:
columns = career_stats_dict['resultSets'][0]['headers']
result_df = pd.DataFrame(career_stats_list, columns=columns)
result_df

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,76001,1990-91,00,1610612757,POR,23.0,43,0.0,290.0,55,...,0.568,27.0,62.0,89.0,12,4.0,12.0,22.0,39,135
1,76001,1991-92,00,1610612757,POR,24.0,71,1.0,934.0,178,...,0.752,81.0,179.0,260.0,30,25.0,16.0,66.0,132,432
2,76001,1992-93,00,1610612749,MIL,25.0,12,0.0,159.0,26,...,0.750,12.0,25.0,37.0,10,6.0,4.0,13.0,24,64
3,76001,1992-93,00,1610612738,BOS,25.0,63,52.0,1152.0,219,...,0.760,114.0,186.0,300.0,17,19.0,22.0,84.0,165,514
4,76001,1992-93,00,0,TOT,25.0,75,52.0,1311.0,245,...,0.759,126.0,211.0,337.0,27,25.0,26.0,97.0,189,578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14228,1626145,2019-20,00,1610612763,MEM,24.0,65,6.0,1232.0,197,...,0.741,9.0,94.0,103.0,285,59.0,6.0,55.0,44,484
14229,1626145,2020-21,00,1610612763,MEM,25.0,70,9.0,1223.0,178,...,0.911,21.0,119.0,140.0,259,64.0,6.0,48.0,31,442
14230,1626145,2021-22,00,1610612763,MEM,26.0,73,23.0,1549.0,249,...,0.818,17.0,159.0,176.0,324,66.0,2.0,46.0,32,632
14231,1626145,2022-23,00,1610612763,MEM,27.0,80,22.0,1939.0,311,...,0.800,28.0,172.0,200.0,417,83.0,6.0,74.0,32,823
14232,1626145,2023-24,00,1610612764,WAS,27.0,66,66.0,1933.0,326,...,0.800,20.0,159.0,179.0,485,71.0,18.0,66.0,48,790

In [11]:
# Assuming 'id' is the common column between players_df and result_df
result_df['full_name'] = result_df['PLAYER_ID'].map(players_df.set_index('id')['full_name'])

result_df

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,full_name
0,76001,1990-91,00,1610612757,POR,23.0,43,0.0,290.0,55,...,27.0,62.0,89.0,12,4.0,12.0,22.0,39,135,Alaa Abdelnaby
1,76001,1991-92,00,1610612757,POR,24.0,71,1.0,934.0,178,...,81.0,179.0,260.0,30,25.0,16.0,66.0,132,432,Alaa Abdelnaby
2,76001,1992-93,00,1610612749,MIL,25.0,12,0.0,159.0,26,...,12.0,25.0,37.0,10,6.0,4.0,13.0,24,64,Alaa Abdelnaby
3,76001,1992-93,00,1610612738,BOS,25.0,63,52.0,1152.0,219,...,114.0,186.0,300.0,17,19.0,22.0,84.0,165,514,Alaa Abdelnaby
4,76001,1992-93,00,0,TOT,25.0,75,52.0,1311.0,245,...,126.0,211.0,337.0,27,25.0,26.0,97.0,189,578,Alaa Abdelnaby
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14228,1626145,2019-20,00,1610612763,MEM,24.0,65,6.0,1232.0,197,...,9.0,94.0,103.0,285,59.0,6.0,55.0,44,484,Tyus Jones
14229,1626145,2020-21,00,1610612763,MEM,25.0,70,9.0,1223.0,178,...,21.0,119.0,140.0,259,64.0,6.0,48.0,31,442,Tyus Jones
14230,1626145,2021-22,00,1610612763,MEM,26.0,73,23.0,1549.0,249,...,17.0,159.0,176.0,324,66.0,2.0,46.0,32,632,Tyus Jones
14231,1626145,2022-23,00,1610612763,MEM,27.0,80,22.0,1939.0,311,...,28.0,172.0,200.0,417,83.0,6.0,74.0,32,823,Tyus Jones
14232,1626145,2023-24,00,1610612764,WAS,27.0,66,66.0,1933.0,326,...,20.0,159.0,179.0,485,71.0,18.0,66.0,48,790,Tyus Jones

### All Star players Crawling

In [12]:
# Initialize an empty list to store the data
data = []
year_text = None  # Initialize year_text outside the loop

# Fetch the HTML content
url = 'https://www.justallstar.com/nba-all-star-game/player-lists/rosters/#1547322049361-993feb14-2aa3'
response = requests.get(url)
html_content = response.text

# Parse the HTML content
soup = BeautifulSoup(html_content, 'html.parser')
# Extract data from td tags and append to the list
for index, td in enumerate(soup.find_all('td')):
    td_text = td.get_text().strip()
    
    if index % 2 == 0:  # Every second td
        if td.a:  # Check if td contains an 'a' tag
            year_text = td.a.get_text()  # Update year_text if it's a year
        else:
            data.append({'Player': td_text, 'Year': year_text})

# Create a DataFrame from the list of dictionaries
all_stars_df = pd.DataFrame(data)

In [13]:
all_stars_df = all_stars_df[(all_stars_df['Player'] != '')&(all_stars_df['Player'] != 'EAST')&(all_stars_df['Player'] != 'WEST')&(~all_stars_df['Player'].str.contains('Team'))]
all_stars_df['Year'].fillna('2019', inplace=True)

# Reset the index after filtering rows
all_stars_df.reset_index(drop=True, inplace=True)

all_stars_df

             Player  Year
0      LeBron James  2019
1     Small Forward  2019
2      Kevin Durant  2019
3     Small Forward  2019
4      Kyrie Irving  2019
...             ...   ...
1676    Larry Foust  1951
1677      Red Rocha  1951
1678    Frank Brian  1951
1679   Dick McGuire  1951
1680    Fred Schaus  1951

[1681 rows x 2 columns]

### Add id column

In [14]:
# Merge all_stars_df with players_df to get the corresponding IDs
all_stars_with_ids = pd.merge(all_stars_df, players_df[['id', 'full_name']], how='left', left_on='Player', right_on='full_name')

# Drop the redundant 'full_name' column
all_stars_with_ids.drop('full_name', axis=1, inplace=True)
all_stars_with_ids['id'] = all_stars_with_ids['id'].astype(str).replace('\.0', '', regex=True)

In [15]:
# Remove rows with 'NUN' in the 'id' column
all_stars_with_ids = all_stars_with_ids[all_stars_with_ids['id'] != 'nan']

# Remove duplicates
all_stars_with_ids = all_stars_with_ids.drop_duplicates()

# Display the resulting DataFrame
all_stars_with_ids

             Player  Year      id
0      LeBron James  2019    2544
2      Kevin Durant  2019  201142
4      Kyrie Irving  2019  202681
6     Kawhi Leonard  2019  202695
8      James Harden  2019  201935
...             ...   ...     ...
1700    Larry Foust  1951   76744
1701      Red Rocha  1951   77999
1702    Frank Brian  1951   76250
1703   Dick McGuire  1951   77537
1704    Fred Schaus  1951   78075

[1579 rows x 3 columns]

### Crawling All Star stats

In [19]:
from nba_api.stats.endpoints import playercareerstats
career_stats_list1 = []

for index, row in all_stars_with_ids.iterrows():

    player_id = row['id']
    career = playercareerstats.PlayerCareerStats(player_id=str(player_id)) 
    career_stats_dict = career.get_dict()
    player_stats = career_stats_dict['resultSets'][0]['rowSet']
    

    career_stats_list1.extend(player_stats)

KeyboardInterrupt:

In [20]:
columns = career_stats_dict['resultSets'][0]['headers']
allstars_stats = pd.DataFrame(career_stats_list1, columns=columns)
allstars_stats

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,2544,2003-04,00,1610612739,CLE,19.0,79,79,3120.0,622,...,0.754,99,333,432,465,130,58,273,149,1654
1,2544,2004-05,00,1610612739,CLE,20.0,80,80,3388.0,795,...,0.750,111,477,588,577,177,52,262,146,2175
2,2544,2005-06,00,1610612739,CLE,21.0,79,79,3361.0,875,...,0.738,75,481,556,521,123,66,260,181,2478
3,2544,2006-07,00,1610612739,CLE,22.0,78,78,3190.0,772,...,0.698,83,443,526,470,125,55,250,171,2132
4,2544,2007-08,00,1610612739,CLE,23.0,75,74,3027.0,794,...,0.712,133,459,592,539,138,81,255,165,2250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,203114,2019-20,00,1610612749,MIL,28.0,62,59,1853.0,471,...,0.916,44,338,382,265,53,7,137,142,1297
245,203114,2020-21,00,1610612749,MIL,29.0,68,68,2269.0,511,...,0.898,54,352,406,370,74,9,178,160,1385
246,203114,2021-22,00,1610612749,MIL,30.0,66,66,2141.0,452,...,0.890,41,315,356,358,76,18,190,160,1325
247,203114,2022-23,00,1610612749,MIL,31.0,33,19,801.0,177,...,0.902,28,112,140,163,23,5,71,68,497
248,203114,2023-24,00,1610612749,MIL,32.0,46,46,1215.0,263,...,0.837,31,172,203,239,40,15,100,116,691

### Combine the data frames

In [21]:
# Assuming both DataFrames have the same columns
combined_df = pd.concat([result_df, allstars_stats], ignore_index=True)

combined_df = combined_df.drop_duplicates(subset=['PLAYER_ID', 'SEASON_ID','TEAM_ID'])

# Print the DataFrame after removing duplicates
combined_df

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,full_name
0,76001,1990-91,00,1610612757,POR,23.0,43,0.0,290.0,55,...,27.0,62.0,89.0,12,4.0,12.0,22.0,39,135,Alaa Abdelnaby
1,76001,1991-92,00,1610612757,POR,24.0,71,1.0,934.0,178,...,81.0,179.0,260.0,30,25.0,16.0,66.0,132,432,Alaa Abdelnaby
2,76001,1992-93,00,1610612749,MIL,25.0,12,0.0,159.0,26,...,12.0,25.0,37.0,10,6.0,4.0,13.0,24,64,Alaa Abdelnaby
3,76001,1992-93,00,1610612738,BOS,25.0,63,52.0,1152.0,219,...,114.0,186.0,300.0,17,19.0,22.0,84.0,165,514,Alaa Abdelnaby
4,76001,1992-93,00,0,TOT,25.0,75,52.0,1311.0,245,...,126.0,211.0,337.0,27,25.0,26.0,97.0,189,578,Alaa Abdelnaby
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14477,203114,2019-20,00,1610612749,MIL,28.0,62,59.0,1853.0,471,...,44.0,338.0,382.0,265,53.0,7.0,137.0,142,1297,NaN
14478,203114,2020-21,00,1610612749,MIL,29.0,68,68.0,2269.0,511,...,54.0,352.0,406.0,370,74.0,9.0,178.0,160,1385,NaN
14479,203114,2021-22,00,1610612749,MIL,30.0,66,66.0,2141.0,452,...,41.0,315.0,356.0,358,76.0,18.0,190.0,160,1325,NaN
14480,203114,2022-23,00,1610612749,MIL,31.0,33,19.0,801.0,177,...,28.0,112.0,140.0,163,23.0,5.0,71.0,68,497,NaN
14481,203114,2023-24,00,1610612749,MIL,32.0,46,46.0,1215.0,263,...,31.0,172.0,203.0,239,40.0,15.0,100.0,116,691,NaN

In [22]:
# Assuming 'id' is the common column between players_df and result_df
combined_df['full_name'] = combined_df['PLAYER_ID'].map(players_df.set_index('id')['full_name'])

### Fix Year column

In [23]:
combined_df['Year'] = combined_df['SEASON_ID'].str.split('-').str[0]

combined_df

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,full_name,Year
0,76001,1990-91,00,1610612757,POR,23.0,43,0.0,290.0,55,...,62.0,89.0,12,4.0,12.0,22.0,39,135,Alaa Abdelnaby,1990
1,76001,1991-92,00,1610612757,POR,24.0,71,1.0,934.0,178,...,179.0,260.0,30,25.0,16.0,66.0,132,432,Alaa Abdelnaby,1991
2,76001,1992-93,00,1610612749,MIL,25.0,12,0.0,159.0,26,...,25.0,37.0,10,6.0,4.0,13.0,24,64,Alaa Abdelnaby,1992
3,76001,1992-93,00,1610612738,BOS,25.0,63,52.0,1152.0,219,...,186.0,300.0,17,19.0,22.0,84.0,165,514,Alaa Abdelnaby,1992
4,76001,1992-93,00,0,TOT,25.0,75,52.0,1311.0,245,...,211.0,337.0,27,25.0,26.0,97.0,189,578,Alaa Abdelnaby,1992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14477,203114,2019-20,00,1610612749,MIL,28.0,62,59.0,1853.0,471,...,338.0,382.0,265,53.0,7.0,137.0,142,1297,Khris Middleton,2019
14478,203114,2020-21,00,1610612749,MIL,29.0,68,68.0,2269.0,511,...,352.0,406.0,370,74.0,9.0,178.0,160,1385,Khris Middleton,2020
14479,203114,2021-22,00,1610612749,MIL,30.0,66,66.0,2141.0,452,...,315.0,356.0,358,76.0,18.0,190.0,160,1325,Khris Middleton,2021
14480,203114,2022-23,00,1610612749,MIL,31.0,33,19.0,801.0,177,...,112.0,140.0,163,23.0,5.0,71.0,68,497,Khris Middleton,2022
14481,203114,2023-24,00,1610612749,MIL,32.0,46,46.0,1215.0,263,...,172.0,203.0,239,40.0,15.0,100.0,116,691,Khris Middleton,2023

### Add All Star column

In [24]:
# Create a new column named 'All_Star' in result_df
combined_df['All_Star'] = 0

# For each player in all_stars_df
for index, row in all_stars_df.iterrows():
    player_name = row['Player']
    year = row['Year']
    
    # Check if there is a player with the same name and year in result_df
    mask = (combined_df['full_name'] == player_name) & (combined_df['Year'] == year)
    combined_df.loc[mask, 'All_Star'] = 1

combined_df[combined_df['All_Star'] == 1]
combined_df.head()

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,REB,AST,STL,BLK,TOV,PF,PTS,full_name,Year,All_Star
0,76001,1990-91,00,1610612757,POR,23.0,43,0.0,290.0,55,...,89.0,12,4.0,12.0,22.0,39,135,Alaa Abdelnaby,1990,0
1,76001,1991-92,00,1610612757,POR,24.0,71,1.0,934.0,178,...,260.0,30,25.0,16.0,66.0,132,432,Alaa Abdelnaby,1991,0
2,76001,1992-93,00,1610612749,MIL,25.0,12,0.0,159.0,26,...,37.0,10,6.0,4.0,13.0,24,64,Alaa Abdelnaby,1992,0
3,76001,1992-93,00,1610612738,BOS,25.0,63,52.0,1152.0,219,...,300.0,17,19.0,22.0,84.0,165,514,Alaa Abdelnaby,1992,0
4,76001,1992-93,00,0,TOT,25.0,75,52.0,1311.0,245,...,337.0,27,25.0,26.0,97.0,189,578,Alaa Abdelnaby,1992,0

### Create CSV file

In [ ]:
data.to_csv("NBA_df_AllStars.csv", index=False)